[build]
builder = "Dockerfile"
dockerfilepath = "RideShare/Dockerfile"  # Path to your Dockerfile

[deploy]
startCommand = "dotnet RideShare.dll"
restartPolicyType = "always"
healthCheckPath = "/health"
